---
title: "makeReport"
author: "Montgomery Inman"
date: "2024-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Creating the stats for the color codings in the gt table

epaPerPlayDF = pbp2023 %>% group_by(game_id, pos_team) %>%
  summarise(epa = sum(EPA),
            plays = n(),
            epaPerPlay = epa / plays) %>%
  arrange(desc(epaPerPlay))

epaPerPassDF = pbp2023 %>% filter(pass == 1) %>%
  group_by(game_id, pos_team) %>%
  summarise(epa = sum(EPA),
            plays = n(),
            yardsGained = sum(yards_gained),
            epaPerPass = epa / plays,
            yardsPerCompletion = (yardsGained / plays)) %>%
  arrange(desc(yardsPerCompletion)) %>%
  filter(plays > 9)

epaPerRushDF = pbp2023 %>% filter(rush == 1) %>%
  group_by(game_id, pos_team) %>%
  summarise(epa = sum(EPA),
            plays = n(),
            epaPerRush = epa / plays) %>%
  arrange(desc(epaPerRush)) %>%
  filter(plays > 9)


yardsPerPlayDF = pbp2023 %>% group_by(game_id, pos_team) %>%
  summarise(total_yards_gained = sum(yards_gained),
            plays = n(),
            yardsPerPlay = total_yards_gained / plays) %>%
  arrange(desc(yardsPerPlay))
```

```{r}
#Creating the gt table
dfForGt %>%
  gt() %>%
  cols_move(
    columns = 1,
    after = 2
  ) %>% 
  cols_align(
  align = "center",
  columns = everything()
) %>% 
  opt_table_font(
  font = "Coolvetica",
) %>%
  tab_row_group("Efficiency", c(2:4, 15)) %>%
  tab_row_group("Passing", c(5:9)) %>%
  tab_row_group("Rushing", c(10:14)) %>%
  row_group_order(groups = c(NA, "Efficiency", "Passing", "Rushing")) %>%
  tab_style(
    style = list(
      cell_text(align = "center")  # Align text to the center
    ),
    locations = cells_row_groups()
  ) %>%
  data_color(
    columns = c(2,3),
    rows = Stat == "Yards / Rush",
    colors = scales::col_quantile(
      palette = "RdYlGn",
      domain = combined_data_team_stats$yards_per_rush_attempt,
      na.color = "#FFFFFF00"
    )
  ) %>%
  data_color(
    columns = c(2,3),
    rows = Stat == "Stuff Rate",
    colors = scales::col_quantile(
      palette = "RdYlGn",
      domain = combined_data_adv_stats$rushing_stuff_rate,
      na.color = "#FFFFFF00",
      reverse = T
    )
  ) %>%
  data_color(
    columns = c(2,3),
    rows = Stat == "EPA / Play",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = epaPerPlayDF$epaPerPlay,
      na.color = "#FFFFFF00",
    )
  ) %>% 
  data_color(
    columns = c(2,3),
    rows = Stat == "EPA / Pass",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = epaPerPassDF$epaPerPass,
      na.color = "#FFFFFF00",
    )
  ) %>% 
  data_color(
    columns = c(2,3),
    rows = Stat == "EPA / Rush",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = epaPerRushDF$epaPerRush,
      na.color = "#FFFFFF00",
    )
  ) %>% 
  data_color(
    columns = c(2,3),
    rows = Stat == "Yards / Play",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = yardsPerPlayDF$yardsPerPlay,
      na.color = "#FFFFFF00",
    )
  ) %>% 
  data_color(
    columns = c(2,3),
    rows = Stat == "Success Rate",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = combined_data_adv_stats$success_rates_overall_total,
      na.color = "#FFFFFF00",
    )
  ) %>% 
  data_color(
    columns = c(2,3),
    rows = Stat == "Yards / Completion",
    colors = scales::col_bin(
      palette = "RdYlGn", 
      domain = epaPerPassDF$yardsPerCompletion,
      na.color = "#FFFFFF00",
    )
  ) %>%
  cols_label(
    Stat = html("")
  ) %>% text_replace(
    pattern = "Score",
    replacement = "Final Score"
  ) %>% 
   fmt_number(
    rows = c(1, 8, 9, 13, 14),
    decimals = 0 
  ) %>%
   fmt_number(
    rows = c(2, 5, 10),
    decimals = 3
  ) %>%
   fmt_number(
    rows = c(3, 6, 11),
    decimals = 2
  ) %>%
   fmt_percent(
    rows =  c(4, 7, 12, 15),
    decimals = 1
  )
```


Make Win Probability Chart:

```{r}

```


Combine:

```{r}

```





