---
title: "test"
author: "Montgomery Inman"
date: "2024-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(cfbfastR)
library(cfbplotR)
library(tidyverse)
library(gt)
```

Pull Data:

```{r}
team = "Iowa State"
year = 2023
week = 12

#Getting pbp data
pbpForEpa = cfbd_pbp_data(year = year, team = team, week = week, epa_wpa = T) %>%
  filter(down > 0,
         !str_detect(play_text, "Kneel"))

#Getting gameid for the game
gameid = pbpForEpa$game_id[1]

#Getting advanced game log data
advancedBox = cfbd_game_box_advanced(gameid, long = F) 

#Getting game team stats
teamStats = cfbd_game_team_stats(year = year, game_id = gameid)

teamStats = teamStats %>% separate_wider_delim(completion_attempts, delim = "-", names = c("completions", "attempts"))

teamStats = teamStats %>% separate_wider_delim(third_down_eff, delim = "-", names = c("thirdDownCompleted", "thirdDownAttempts"))


```

Make gt() table:

```{r}
#Seperating the team stats df with home and away
homeTeamStats = teamStats %>% filter(home_away == "home")
awayTeamStats = teamStats %>% filter(home_away == "away")

#Seperating the advanced box df with home and away
homeAdvBox = advancedBox %>% filter(team == pbp$home[1])
awayAdvBox = advancedBox %>% filter(team == pbp$away[1])

#Calculating EPA things
homePBP = pbpForEpa %>%
  filter(pos_team == pbpForEpa$home[1])

awayPBP = pbpForEpa %>%
  filter(pos_team == pbpForEpa$away[1])

homePBPpass = homePBP %>%
  filter(pass == 1)

awayPBPpass = awayPBP %>%
  filter(pass == 1)

homePBPrush = homePBP %>%
  filter(rush == 1)

awayPBPrush = awayPBP %>%
  filter(rush == 1)

homeEPAperPlay = sum(homePBP$EPA, na.rm = T) / nrow(homePBP)
awayEPAperPlay = sum(awayPBP$EPA, na.rm = T) / nrow(awayPBP)

homeEPAperPass = sum(homePBPpass$EPA, na.rm = T) / nrow(homePBPpass)
awayEPAperPass = sum(awayPBPpass$EPA, na.rm = T) / nrow(awayPBPpass)

homeEPAperRush = sum(homePBPrush$EPA, na.rm = T) / nrow(homePBPrush)
awayEPAperRush = sum(awayPBPrush$EPA, na.rm = T) / nrow(awayPBPrush)

#Creating the data frame for the gt table
dfForGt = data.frame(
  "Stat" = c("Team", 
             "Score",
             "EPA / Play",
             "Yards / Play",
             "Success Rate",
             "Poss Time",
             "EPA / Pass",
             "Yards / Completion",
             "Completion %",
             "Attempts",
             "Yards",
             "EPA / Rush",
             "Yards / Rush",
             "Stuff Rate",
             "Attempts",
             "Yards",
             "First Downs",
             "Third Down %"
  ),
  "Home" = c(pbpForEpa$home[1], 
             homeTeamStats$points,
             homeEPAperPlay,
             as.numeric(homeTeamStats$total_yards) / homeAdvBox$ppa_plays, 
             homeAdvBox$success_rates_overall_total,
             homeTeamStats$possession_time,
             homeEPAperPass,
             as.numeric(homeTeamStats$net_passing_yards) / as.numeric(homeTeamStats$completions),
             as.numeric(homeTeamStats$completions) / as.numeric(homeTeamStats$attempts),
             homeTeamStats$attempts,
             homeTeamStats$net_passing_yards,
             homeEPAperRush,
             homeTeamStats$yards_per_rush_attempt,
             homeAdvBox$rushing_stuff_rate,
             homeTeamStats$rushing_attempts,
             homeTeamStats$rushing_yards,
             homeTeamStats$first_downs,
             as.numeric(homeTeamStats$thirdDownCompleted) / as.numeric(homeTeamStats$thirdDownAttempts)),
  "Away" = c(pbpForEpa$away[1],
             awayTeamStats$points,
             awayEPAperPlay,
             as.numeric(awayTeamStats$total_yards) / awayAdvBox$ppa_plays,
             awayAdvBox$success_rates_overall_total,
             awayTeamStats$possession_time,
             awayEPAperPass,
             as.numeric(awayTeamStats$net_passing_yards) / as.numeric(awayTeamStats$completions),
             as.numeric(awayTeamStats$completions) / as.numeric(awayTeamStats$attempts),
             awayTeamStats$attempts,
             awayTeamStats$net_passing_yards,
             awayEPAperRush,
             awayTeamStats$yards_per_rush_attempt,
             awayAdvBox$rushing_stuff_rate,
             awayTeamStats$rushing_attempts,
             awayTeamStats$rushing_yards,
             awayTeamStats$first_downs,
             as.numeric(awayTeamStats$thirdDownCompleted) / as.numeric(awayTeamStats$thirdDownAttempts))
)

```

Calculate percentiles for color grading gt():
```{r}
#Getting data for team stats 
combined_data_team_stats <- data.frame()
weeksForPercentiles = c(1:15)

for (weeks in weeksForPercentiles) {
  temp = cfbd_game_team_stats(
  year = 2023,
  week = weeks,
  season_type = "regular",
  team = NULL,
  conference = NULL,
  game_id = NULL,
  rows_per_team = 1
  )
  
  combined_data_team_stats <- rbind(combined_data_team_stats, temp)
}

combined_data_team_stats[78] = sapply(combined_data_team_stats[78], as.numeric)
combined_data_team_stats = as.data.frame(combined_data_team_stats)

#Getting data for adv stats
combined_data_adv_stats <- data.frame()
weeksForPercentiles = c(1:15)

for (weeks in weeksForPercentiles) {
  temp = cfbd_game_info(
    year = year,
    week = weeks,
    season_type = "regular",
    division = "fbs",
  )
  
  weekData = rbind(weekData, temp)
  
  gameIds = weekData$game_id
}

for (game in gameIds) {
  temp = cfbd_game_box_advanced(
    game_id = game,
  )
  
  combined_data_adv_stats <- rbind(combined_data_adv_stats, temp)
}


#Getting play by play data
pbp2023 = cfbd_pbp_data(year = year, epa_wpa = T) %>%
  filter(down > 0,
         !str_detect(play_text, "Kneel"))

#calculating percentiles for team stats


#calculating percentiles for adv stats


#calculating percentiles for pbp

```

```{r}
str(dfForGt)


dfForGt %>%
  gt() %>%
  data_color(
    columns = vars(Home),
    rows = Stat == "EPA / Play",
    colors = scales::col_quantile(
      palette = "Blues",
      domain = combined_data_adv_stats$ppa_overall_total,
      na.color = "#FFFFFF00"
    )
  )

```



Make Win Probability Chart:

```{r}

```


Combine:

```{r}

```









